Add ssr option, allow negative and percentage values for snapPoints
Temzasse/react-modal-sheet pull request #22
Opened 2021-04-25 18:59 UTC by MarkusWendorf

This PR adds an `ssr` option that outputs the sheet content to the DOM on the server side (if isOpen=true).
In addition it adds the option to use negative snapPoints (measured from the top) and percentage values (specified as 0.0 to 1.0).

I've added an example for the negative snap points value to `SnapPoints.tsx`.
Is it required to have the snapPoints in descending order (I've added an assertion).

Feel free to comment and thanks for the library.

2021-04-25 21:26 UTC, MarkusWendorf commented on src/sheet.tsx
> +    if (ssr) return sheet;
Don't use portal for ssr, mount wherever the component is in the React Tree.

2021-04-26 07:12 UTC, Temzasse commented
Oh wow this looks great! Thank you! 🙏🏻😊 

On initial glance everything looked good but I'll take a deeper look at it and test it out when I have more time this week.

2021-04-29 18:35 UTC, Temzasse reviewed
Awesome job! 💯 Added a few comments and improvement ideas 🙂

2021-04-29 18:35 UTC, Temzasse commented on src/types.tsx
> +  ssr?: boolean;
What is the reason for this `ssr` prop? Couldn't we use the `isBrowser` variable to automatically detect whether the env is server vs client? (I'm not very familiar with SSR since I haven't used Nextjs etc frameworks that much 😅)

2021-04-29 18:35 UTC, Temzasse commented on src/utils.ts
> +  });
This could be enhance with a window size listener so that the window height is in sync:

```suggestion
  useLayoutEffectSSR(() => {
    const updateHeight = () => setWindowHeight(window.innerHeight);
    window.addEventListener('resize', updateHeight);
    updateHeight();
    return () => window.removeEventListener('resize', updateHeight);
  }, []);
```

2021-04-29 18:35 UTC, Temzasse commented on src/sheet.tsx
> +      snapPoints = snapPoints.map(point => {
This is awesome! 💎✨

2021-04-29 18:35 UTC, Temzasse commented on src/sheet.tsx
> +      snapPoints = snapPoints.map(point => {
We should update the `README.md` to have a mention about negative + % snap point values.

2021-04-29 18:35 UTC, Temzasse commented on src/sheet.tsx
> +    if (ssr) return sheet;
I'm wondering if the empty div trick is needed anymore in the below return statement 🤔 We could maybe just return the portal without the `mounted` checking.

2021-04-29 18:43 UTC, Temzasse commented
@MarkusWendorf do you have any suggestion for an easy way to test SSR? I have very little experience with SSR frameworks and I've been using the `/example` app as a playground for the lib but it's entirely client-side rendered so it doesn't help when I need to test SSR specific things.

2021-05-01 11:39 UTC, MarkusWendorf commented
@Temzasse I provided two tests that check if ssr actually works (in the sense that the <Sheet.Content> is output to the html. To do visual inspection / test, I think the best way would be to setup another example folder with Next.js for example. I can provide a setup tomorrow I think.

2021-05-03 07:20 UTC, Temzasse requested changes
@MarkusWendorf huge thanks for the Next.js example 🙌🏻 

This is looking really nice! ✨ 

The only two remaining things to go over are the `ssr` prop and the `mounted` ternary which was my previous hack for SSR.

2021-05-03 07:20 UTC, Temzasse commented on src/types.tsx
> +  ssr?: boolean;
@MarkusWendorf can you elaborate on the need for the `ssr` prop instead of deducting it from the lack of window object?

2021-05-03 07:20 UTC, Temzasse commented on src/sheet.tsx
> +      ssr = true,
The default value for `ssr` should be false, right? Could we deduct it from window:

```js
ssr = typeof window === 'undefined',
```

Also please check my other comment about the need for `ssr` prop in the first place 🙂

2021-05-03 07:20 UTC, Temzasse commented on src/sheet.tsx
> +    if (ssr) return sheet;
@MarkusWendorf do you think the `mounted` ternary could be removed since we are handling the SSR case above? So we could just do: 

```js
if (ssr) return sheet;

return ReactDOM.createPortal(sheet, document.body)
```

2021-05-29 11:51 UTC, Temzasse commented
Thank you a lot @MarkusWendorf for this PR! 🙏🏻 

I finalized the work in another [PR](https://github.com/Temzasse/react-modal-sheet/pull/33) in and merged it into master so I will close this PR 🙂

2021-05-29 11:51 UTC, closed without merging