Allow sheet to be height of content of the sheet
Temzasse/react-modal-sheet pull request #83
Opened 2022-06-25 02:26 UTC by nickgraffis

This seems to help with #69 however notably it does not dynamically update the sheet height.

You can click the box to create more boxes if you look at the example added. This won't make the sheet bigger until it is closed and reopened.

2022-07-24 19:43 UTC, Temzasse requested changes
Thanks for this! I still have to test this locally but I decided to comment on stuff already by just looking at the code 🙂

2022-07-24 19:43 UTC, Temzasse commented on src/SheetContainer.tsx
> +      <>
This fragment seems unnecessary

2022-07-24 19:43 UTC, Temzasse commented on src/SheetContainer.tsx
> +            ...(!useContentHeight && { height: sheetHeight }),
Could we use a different prop name here since I'm not the biggest fan of using `useX` names that resemble names of hooks. So let's maybe use something like:

```ts
sheetHeight?: 'full' | 'content'
```

Alternatively we could try to align with the naming that Apple uses [here](https://developer.apple.com/design/human-interface-guidelines/components/presentation/sheets#ios-ipados) by using `detent` as prop name:

```ts
detent: 'full-height' | 'content-height'
```

Altho as a non-native english speaker the word `detent` is a bit weird to me so maybe `sheetHeight` is a better name 😄

2022-07-24 20:03 UTC, Temzasse commented
I wonder how should this work in conjunction with `snapPoints` 🤔 

Now if you set snap points eg. to `snapPoints={[0.9, 0.5, 0.1]}` in your example it will allow you to drag the sheet beyond the content height which will cause UI issues:

<img width="462" alt="Screenshot 2022-07-24 at 23 00 49" src="https://user-images.githubusercontent.com/6152032/180663854-b6012b7f-3019-4deb-8030-7930d677af9e.png">

2022-07-24 20:43 UTC, Temzasse commented
> I wonder how should this work in conjunction with `snapPoints` 🤔
> 
> Now if you set snap points eg. to `snapPoints={[0.9, 0.5, 0.1]}` in your example it will allow you to drag the sheet beyond the content height which will cause UI issues:
> 
> <img alt="Screenshot 2022-07-24 at 23 00 49" width="462" src="https://user-images.githubusercontent.com/6152032/180663854-b6012b7f-3019-4deb-8030-7930d677af9e.png">

One solution could be to disallow using both `sheetHeight="content"` and `snapPoints` at the same time. I have hard time formulating how should those two even work together if we were to allow using them both at the same time 🤔

2022-07-25 17:51 UTC, nickgraffis commented
Possibly for the `snapPoints` issue we could just have the content height property take precidence. Let me toy with it, but thinking that if you set both `snapPoints` and `sheetHeight` to `content-height` that the content height would take precidence.

So if the content height was less than the height that the chosen `snapPoint` would need, the content height would be used.

I'll look into both of these.

Thanks!

2022-07-26 09:27 UTC, Temzasse commented
> Possibly for the `snapPoints` issue we could just have the content height property take precidence. Let me toy with it, but thinking that if you set both `snapPoints` and `sheetHeight` to `content-height` that the content height would take precidence.
> 
> 
> 
> So if the content height was less than the height that the chosen `snapPoint` would need, the content height would be used.
> 
> 
> 
> I'll look into both of these.
> 
> 
> 
> Thanks!

This sounds like a viable solution 👍

I played around with measuring the content height with [`react-use-measure`](https://github.com/pmndrs/react-use-measure) to get the actual height value in JS. Didn't have enough time to get anything proper working so let's see what you come up with 😄 If you end up using that lib too then one thing that I had to change was that the sheet container `animate` needs to be delayed one render cycle so that we are able to measure the content height before showing the sheet.

2022-10-07 07:10 UTC, Temzasse commented
@nickgraffis have you by any chance had the time to work on this? 😊

2022-10-07 19:23 UTC, Temzasse commented
I have worked on a potential implementation but I need to test it a bit more before I can release it. I leaning towards **not** supporting `snapPoints` when the sheet height is set to follow the content height. I'm also considering using the `detent` naming for the prop even though it is not very common term in English - I like how it matches with the Apple bottom sheet terminology.

2022-10-08 05:21 UTC, nickgraffis commented
😂 I have not had a chance - but this was a good ping as a reminder. I see your notes above. I'll take swing this weekend

2022-10-09 18:42 UTC, Temzasse commented
@nickgraffis I hope you have had a great weekend! I had some time to work on this feature so here's my suggestion for the implementation: https://github.com/Temzasse/react-modal-sheet/pull/96

If you haven't gotten too far with your implementation would you be okay with taking a look at the PR and give feedback? 🙂 

If everything looks okay I can merge and release it during next week.

2022-10-10 16:34 UTC, nickgraffis commented
Closing because of #96

2022-10-10 16:34 UTC, closed without merging