Hide y animation if user prefers reduced motion
Temzasse/react-modal-sheet pull request #97
Opened 2022-10-11 18:55 UTC by adamstambouli

First of all, thanks @Temzasse for putting this library together! Was great to use for our project.

This PR adds better support for a11y if a user prefers reduced motion. The component automatically checks for the user's preferences using Framer Motion's [`useReducedMotion` hook](https://www.framer.com/docs/guide-accessibility/#usereducedmotion). An override is also exposed in `prefersReducedMotion`, a prop that can be provided to the Sheet root.

When either of these flags are `true`, the sheet spring animation is replaced with an instant value update. The opacity of the sheet is also updated so that the sheet is hidden during the height (y-value) update.

2022-10-11 19:42 UTC, Temzasse requested changes
Thank you very much! Absolutely fantastic work! 💎✨ 

Overall looks very good - just left a question about the usage of `opacity` to understand it better and a few improvement ideas 🙂

2022-10-11 19:42 UTC, Temzasse commented on src/SheetContainer.tsx
> +          opacity,
Do we want to keep the initial mount animation even if `prefersReducedMotion` is true?

I played around with changing the animation transition in `SheetContainer` to make the enter and exit animations happen instantly if the user prefers reduced motion:

```tsx
const transition = prefersReducedMotion
  ? { type: 'tween', duration: 0.01 }
  : { type: 'spring', ...springConfig };

return (
  <motion.div
    // other props...
    animate={{ y: initialY, transition }}
    exit={{ y: windowHeight, transition }}
  >
    {children}
  </motion.div>
);
```

What do you think? 🙂

2022-10-11 19:42 UTC, Temzasse commented on src/sheet.tsx
> +    const opacity = useMotionValue(0);
Curious to know why the opacity is needed? If the `y` value is changed instantly does it make a difference to set the opacity to 0 and then almost immediately to 1? 🤔 

I tested this locally and the opacity seems to stay 0 when the sheet is opened.

2022-10-11 19:42 UTC, Temzasse commented on src/sheet.tsx
> +      opacity,
`prefersReducedMotion` was added to `SheetContextType` type but it's not passed here.

2022-10-11 19:42 UTC, Temzasse commented on README.md
> +| `prefersReducedMotion` | no       | false            | Hide sheet animations (sheet instantly snaps to desired location).
NIT: Would "skip" be more accurate word here than "hide"?

2022-10-12 07:52 UTC, Temzasse commented
If you are developing this by running `yarn start` in both the root and the example you should note that the example app doesn't refresh if you make changes in the lib code. You have to restart parcel in the example app after every lib code change 😅

I really need to update the bundler setup to make the DX better...

2022-10-12 13:48 UTC, adamstambouli commented on src/SheetContainer.tsx
> +          opacity,
Nice, good idea. Love it! Making that change shortly.

2022-10-12 13:49 UTC, adamstambouli commented on src/sheet.tsx
> +      opacity,
Ah thanks for the catch. Fixing shortly.

2022-10-12 13:49 UTC, adamstambouli commented on README.md
> +| `prefersReducedMotion` | no       | false            | Hide sheet animations (sheet instantly snaps to desired location).
Yeah, I'm onboard with that. Making that change shortly.

2022-10-12 13:49 UTC, adamstambouli commented
> If you are developing this by running yarn start in both the root and the example you should note that the example app doesn't refresh if you make changes in the lib code. You have to restart parcel in the example app after every lib code change 😅

Haha thanks for the head's up! I wasn't sure how to preview changes without using the entire repo as a local npm package 😬 

Going to make changes as you suggested shortly!

2022-10-12 14:22 UTC, adamstambouli commented
Just pushed changes with your feedback. I wasn't able to test it locally (I use `pnpm` for package deps) and got this error:

```
example git:(master) ✗ pnpm start

> example@1.0.0 start /Users/astambouli/code/react-modal-sheet/example
> parcel index.html --no-cache

Server running at http://localhost:1234
🚨 Build failed.

@parcel/core: Failed to resolve 'scheduler/tracing' from 
'[REDACTED]/react-modal-sheet/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js'

  [REDACTED]/react-modal-sheet/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:19:23
    18 | var Scheduler = require('scheduler');
  > 19 | var tracing = require('scheduler/tracing');
  >    |                       ^^^^^^^^^^^^^^^^^^^
    20 | 
    21 | var ReactSharedInternals = React.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED;

@parcel/resolver-default: Cannot load file '../../../../../scheduler/tracing-profiling' in 
'../node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs'.
```

Let me know how well this works and if you have any other feedback.

2022-10-12 15:23 UTC, Temzasse commented on src/sheet.tsx
> +    const opacity = useMotionValue(0);
Okay now I understand it better, thanks for the explanation! I think that removing the opacity would make the implementation a bit simpler and the opacity change is not noticeable anyway so I don't think it makes sense to have it.

2022-10-12 15:26 UTC, Temzasse commented
> Just pushed changes with your feedback. I wasn't able to test it locally (I use `pnpm` for package deps) and got this error:
> 
> ```
> example git:(master) ✗ pnpm start
> 
> > example@1.0.0 start [REDACTED]/react-modal-sheet/example
> > parcel index.html --no-cache
> 
> Server running at http://localhost:1234
> 🚨 Build failed.
> 
> @parcel/core: Failed to resolve 'scheduler/tracing' from 
> '[REDACTED]/react-modal-sheet/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js'
> 
>   [REDACTED]/react-modal-sheet/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:19:23
>     18 | var Scheduler = require('scheduler');
>   > 19 | var tracing = require('scheduler/tracing');
>   >    |                       ^^^^^^^^^^^^^^^^^^^
>     20 | 
>     21 | var ReactSharedInternals = React.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED;
> 
> @parcel/resolver-default: Cannot load file '../../../../../scheduler/tracing-profiling' in 
> '../node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs'.
> ```
> 
> Let me know how well this works and if you have any other feedback.

Unfortunately I haven't used pnpm at all so I'm not quite sure why this error is happening 😕

I can test your changes when I have some free time.

2022-10-13 17:26 UTC, Temzasse approved these changes
Thank you again! This is great stuff! ⭐

2022-10-13 17:26 UTC, merged